module Hibernate
  module Dialects
    Cache71 = "org.hibernate.dialect.Cache71Dialect"
    DataDirectOracle9 = "org.hibernate.dialect.DataDirectOracle9Dialect"
    DB2390 = "org.hibernate.dialect.DB2390Dialect"
    DB2400 = "org.hibernate.dialect.DB2400Dialect"
    DB2 = "org.hibernate.dialect.DB2Dialect"
    Derby = "org.hibernate.dialect.DerbyDialect"
    Firebird = "org.hibernate.dialect.FirebirdDialect"
    FrontBase = "org.hibernate.dialect.FrontBaseDialect"
    H2 = "org.hibernate.dialect.H2Dialect"
    HSQL = "org.hibernate.dialect.HSQLDialect"
    Informix = "org.hibernate.dialect.InformixDialect"
    Ingres = "org.hibernate.dialect.IngresDialect"
    Interbase = "org.hibernate.dialect.InterbaseDialect"
    JDataStore = "org.hibernate.dialect.JDataStoreDialect"
    Mckoi = "org.hibernate.dialect.MckoiDialect"
    MimerSQL = "org.hibernate.dialect.MimerSQLDialect"
    MySQL5 = "org.hibernate.dialect.MySQL5Dialect"
    MySQL5InnoDB = "org.hibernate.dialect.MySQL5InnoDBDialect"
    MySQL = "org.hibernate.dialect.MySQLDialect"
    MySQLInnoDB = "org.hibernate.dialect.MySQLInnoDBDialect"
    MySQLMyISAM = "org.hibernate.dialect.MySQLMyISAMDialect"
    Oracle9 = "org.hibernate.dialect.Oracle9Dialect"
    Oracle = "org.hibernate.dialect.OracleDialect"
    Pointbase = "org.hibernate.dialect.PointbaseDialect"
    PostgreSQL = "org.hibernate.dialect.PostgreSQLDialect"
    Progress = "org.hibernate.dialect.ProgressDialect"
    RDMSOS2200 = "org.hibernate.dialect.RDMSOS2200Dialect"
    SAPDB = "org.hibernate.dialect.SAPDBDialect"
    SQLServer = "org.hibernate.dialect.SQLServerDialect"
    Sybase11 = "org.hibernate.dialect.Sybase11Dialect"
    SybaseAnywhere = "org.hibernate.dialect.SybaseAnywhereDialect"
    Sybase = "org.hibernate.dialect.SybaseDialect"
    TimesTen = "org.hibernate.dialect.TimesTenDialect"
  end
end